package com.ftlife.plus.partner.parameter;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class CampaignDetailParameter {
    private String campaignDetailId;
    private String campaignHeaderId;
    private String clientFullNameEng;
    private String clientFullNameChi;
    private String clientId;
    private String partyId;
    private String clientGender;
    private String dateOfBirth;
    private String dateOfBirthFrom;
    private String dateOfBirthTo;
    private String birthdayMonth;
    private String languageForCommunication;
    private String deathClaim;
    private String latestPolicyIssueDate;
    private String latestPolicyIssueDateFrom;
    private String latestPolicyIssueDateTo;
    private String firstPolicyIssueDate;
    private String firstPolicyIssueDateFrom;
    private String firstPolicyIssueDateTo;
    private String latestIssuedPolicy;
    private String noOfInForcePolicy;
    private String lastYearPremium;
    private String thisYearPremium;
    private String salesChannel;
    private String produceAgent1Region;
    private String produceAgent1Code;
    private String produceAgent1Name;
    private String produceAgent2Region;
    private String produceAgent2Code;
    private String produceAgent2Name;
    private String servAgentRegion;
    private String servAgentRegionName;
    private String servAgentDistrictCode;
    private String servAgentEmail;
    private String servAgentCode;
    private String servAgentName;
    private String salesManager1;
    private String mobileAreaCode;
    private String mobile;
    private String validity;
    private String email;
    private String mailAddressAreaCode;
    private String foreignIndicator;
    private String mailingAddress1;
    private String mailingAddress2;
    private String mailingAddress3;
    private String mailingAddress4;
    private String mailingAddress5;
    private String optOut;
    private String picsIndicator;
    private String picsIndicatorDate;
    private String picsIndicatorDateFrom;
    private String picsIndicatorDateTo;
    private String directMarketingFtl;
    private String directMarketingFtlDate;
    private String directMarketingFtlDateFrom;
    private String directMarketingFtlDateTo;
    private String directMarketingNwg;
    private String directMarketingNwgDate;
    private String directMarketingNwgDateFrom;
    private String directMarketingNwgDateTo;
    private String bd;
    private String haveP10Account;
    private String communicationChannel;
    private String servicingAgentMobile;
    private String servicingAgentEmail;
    private String servicingAgentStatus;
    private String optIn;
    private String trCode;
    private String remark;
    private String remarkAgent;
    private String createdDate;
    private String createdDateFrom;
    private String createdDateTo;
    private String updatedDate;
    private String updatedDateFrom;
    private String updatedDateTo;
    private String createdBy;
    private String updatedBy;

}
