CREATE TABLE TCampaignDetail (
    campaignDetailId int IDENTITY(1,1) NOT NULL,
    campaignHeaderId int NOT NULL,
    clientFullNameEng VARCHAR(141),
	clientFullNameChi VARCHAR(140),
	clientId VARCHAR(50),
	partyId int,
	clientGender CHAR(1),
	dateOfBirth DATETIME ,
	birthdayMonth VARCHAR(2),
	languageForCommunication CHAR(2),
	deathClaim CHAR(1),
	latestPolicyIssueDate DATETIME ,
	firstPolicyIssueDate DATETIME ,
	latestIssuedPolicy VARCHAR(20),
	noOfInForcePolicy int,
	lastYearPremium int,
	thisYearPremium int,
	salesChannel VARCHAR(4),
	produceAgent1Region VARCHAR(20),
	produceAgent1Code VARCHAR(20),
	produceAgent1Name VARCHAR(150),
	produceAgent2Region VARCHAR(20),
	produceAgent2Code VARCHAR(20),
	produceAgent2Name VARCHAR(150),
	servAgentRegion VARCHAR(4000),
	servAgentRegionName VARCHAR(600),
	servAgentDistrictCode VARCHAR(4000),
	servAgentEmail VARCHAR(4000),
	servAgentCode VARCHAR(20),
	servAgentName VARCHAR(150),
	salesManager1 VARCHAR(50),
	mobileAreaCode VARCHAR(10),
	mobile VARCHAR(20),
	validity CHAR(1),
	email VARCHAR(100),
	mailAddressAreaCode VARCHAR(60),
	foreignIndicator CHAR(1),
	mailingAddress1 VARCHAR(4000),
	mailingAddress2 VARCHAR(4000),
	mailingAddress3 VARCHAR(4000),
	mailingAddress4 VARCHAR(4000),
	mailingAddress5 VARCHAR(4000),
	optOut CHAR(1),
	picsIndicator CHAR(1),
	picsIndicatorDate DATETIME ,
	directMarketingFtl CHAR(1),
	directMarketingFtlDate DATETIME ,
	directMarketingNwg CHAR(1),
	directMarketingNwgDate DATETIME ,
	bd VARCHAR(3),
	haveP10Account CHAR(1),
	communicationChannel CHAR(3),
	servicingAgentMobile VARCHAR(20),
	servicingAgentEmail VARCHAR(100),
	servicingAgentStatus VARCHAR(30),
	optIn CHAR(3),
	remark  VARCHAR(4000),
	remarkAgent  VARCHAR(4000),
    createdDate DATETIME  NOT NULL,
    updatedDate DATETIME  NOT NULL,
    createdBy VARCHAR(200) NOT NULL,
    updatedBy VARCHAR(200) NOT NULL,
	CONSTRAINT  PKTCampaignDetail PRIMARY KEY CLUSTERED (campaignDetailId)
);

DROP TABLE TCampaignDetail;

SELECT * FROM TCampaignDetail;