    CREATE VIEW VCampaignDetailAgent("campaignDetailId", "campaignHeaderId", "clientFullNameEng", "clientFullNameChi", "clientId", "partyId", "clientGender", "dateOfBirth", "birthdayMonth", "languageForCommunication", "deathClaim", "latestPolicyIssueDate", "firstPolicyIssueDate", "latestIssuedPolicy", "noOfInForcePolicy", "lastYearPremium", "thisYearPremium", "salesChannel", "produceAgent1Region", "produceAgent1Code", "produceAgent1Name", "produceAgent2Region", "produceAgent2Code", "produceAgent2Name", "servAgentRegion", "servAgentRegionName", "servAgentDistrictCode", "servAgentEmail", "servAgentCode", "servAgentName", "salesManager1", "mobileAreaCode", "mobile", "validity", "email", "mailAddressAreaCode", "foreignIndicator", "mailingAddress1", "mailingAddress2", "mailingAddress3", "mailingAddress4", "mailingAddress5", "optOut", "picsIndicator", "picsIndicatorDate", "directMarketingFtl", "directMarketingFtlDate", "directMarketingNwg", "directMarketingNwgDate", "bd", "haveP10Account", "communicationChannel", "servicingAgentMobile", "servicingAgentEmail", "servicingAgentStatus", "optIn", "remark", "createdDate", "updatedDate", "createdBy", "updatedBy", "trCode")
     AS
      SELECT
        a.campaignDetailId,
        a.campaignHeaderId,
        a.clientFullNameEng,
        a.clientFullNameChi,
        a.clientId,
        a.partyId,
        a.clientGender,
        a.dateOfBirth,
        a.birthdayMonth,
        a.languageForCommunication,
        a.deathClaim,
        a.latestPolicyIssueDate,
        a.firstPolicyIssueDate,
        a.latestIssuedPolicy,
        a.noOfInForcePolicy,
        a.lastYearPremium,
        a.thisYearPremium,
        a.salesChannel,
        a.produceAgent1Region,
        a.produceAgent1Code,
        a.produceAgent1Name,
        a.produceAgent2Region,
        a.produceAgent2Code,
        a.produceAgent2Name,
        a.servAgentRegion,
        a.servAgentRegionName,
        a.servAgentDistrictCode,
        a.servAgentEmail,
        a.servAgentCode,
        a.servAgentName,
        a.salesManager1,
        a.mobileAreaCode,
        a.mobile,
        a.validity,
        a.email,
        a.mailAddressAreaCode,
        a.foreignIndicator,
        a.mailingAddress1,
        a.mailingAddress2,
        a.mailingAddress3,
        a.mailingAddress4,
        a.mailingAddress5,
        a.optOut,
        a.picsIndicator,
        a.picsIndicatorDate,
        a.directMarketingFtl,
        a.directMarketingFtlDate,
        a.directMarketingNwg,
        a.directMarketingNwgDate,
        a.bd,
        a.haveP10Account,
        a.communicationChannel,
        a.servicingAgentMobile,
        a.servicingAgentEmail,
        a.servicingAgentStatus,
        a.optIn,
        a.remark,
        a.remarkAgent,
        a.createdDate,
        a.updatedDate,
        a.createdBy,
        a.updatedBy,
        b.trCode
        b.trNameEng
    FROM TCampaignDetail a LEFT JOIN TPolicyAssignment b ON a.latestIssuedPolicy = b.policyNumber;


    Drop View VCampaignDetailAgent

    Select * FROM VCampaignDetailAgent